server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:5432/registration?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
